#!/bin/sh -e

isenabled="$(snapctl get isenabled || echo no)"
certpath="$(snapctl get certpath)"
keypath="$(snapctl get keypath)"
grovepath="$(snapctl get grovepath)"
server="$(snapctl get server)"
RELAY_ARGS="-certpath $certpath -keypath $keypath -grovepath $grovepath"

case "$isenabled" in
    "no")
        echo "Relay service is not enabled. Use 'snap set arbor-relay isenabled=yes' to enable then restart the service."
        exit 1
        ;;
    "yes")
        echo "Relay enabled. Starting..."
        relay $RELAY_ARGS
	;;
    *)
        echo "Something went wrong starting the relay..."
        exit 2
        ;;
esac
